FROM shcem/netcore:1.0

COPY . /etc/apt/

# Install .NET CLI dependencies
RUN apt-get update
#RUN apt-get install -y apt-transport-https
#RUN apt-get install -y libgdiplus
#RUN cd /usr/lib
#RUN ln -s libgdiplus.so gdiplus.dll

#RUN apt-get update
RUN apt-get install -y dotnet-dev-1.0.0-preview2-003131

# Trigger the population of the local package cache
ENV NUGET_XMLDOC_MODE skip
RUN mkdir warmup \
    && cd warmup \
    && dotnet new \
    && cd .. \
    && rm -rf warmup \
    && rm -rf /tmp/NuGetScratch